#!/bin/sh

IDN_CMD="$(which idn)"
if [ $? -ne 0 ]; then
    U_ENABLE_IDN=0
fi
if [ ! -f "$BLLIST_IP_FILTER_FILE" ]; then
    U_IP_FILTER=0
fi
if [ ! -f "$BLLIST_FQDN_FILTER_FILE" ]; then
    U_FQDN_FILTER=0
fi
if [ ! -f "$BLLIST_IP_EXCLUDED_FILE" ]; then
    U_IP_EXCLUDED_ENABLE=0
fi
if [ ! -f "$BLLIST_FQDN_EXCLUDED_FILE" ]; then
    U_FQDN_EXCLUDED_ENABLE=0
fi
ENTRIES_ADDITIONAL_FILE_ENABLE=0
if [ -n "$U_ENTRIES_ADDITIONAL_FILE" -a -f "$U_ENTRIES_ADDITIONAL_FILE" ]; then
    ENTRIES_ADDITIONAL_FILE_ENABLE=1
fi

echo | $AWK_CMD -v WGET_CMD="$WGET_CMD" -v WGET_PARAMS="$WGET_PARAMS" \
    -v LOGGER_CMD="$LOGGER_CMD" -v LOGGER_PARAMS="$LOGGER_PARAMS" \
    -v IDN_CMD="$IDN_CMD" -v ENTRIES_ADDITIONAL_FILE_ENABLE="$ENTRIES_ADDITIONAL_FILE_ENABLE" '
    BEGIN {
        stderr = "/dev/stderr";
        ENABLE_LOGGING = ENVIRON["ENABLE_LOGGING"];
        ENABLE_TMP_DOWNLOADS = ENVIRON["ENABLE_TMP_DOWNLOADS"];
        sleep = "sleep " ENVIRON["USER_ENTRIES_REMOTE_DOWNLOAD_TIMEOUT"];
        DOWNLOAD_ATTEMPTS = ENVIRON["USER_ENTRIES_REMOTE_DOWNLOAD_ATTEMPTS"];
        attempt_err_pattern = "User entries download attempt %s: failed [%s:%s]";
        U_NAME = ENVIRON["U_NAME"];
        ENTRIES_ADDITIONAL_FILE=ENVIRON["U_ENTRIES_ADDITIONAL_FILE"];
        U_ENTRIES_REMOTE = ENVIRON["U_ENTRIES_REMOTE"];
        U_USER_ENTRIES_DNS = ENVIRON["U_ENTRIES_DNS"];
        NFT_TABLE = ENVIRON["NFT_TABLE"];
        NFTSET_IP_STRING = ENVIRON["I_NFTSET_IP_STRING"];
        NFTSET_DNSMASQ = ENVIRON["I_NFTSET_DNSMASQ"];
        NFT_TABLE_DNSMASQ = ENVIRON["NFT_TABLE_DNSMASQ"];
        IP_DATA_FILE = ENVIRON["I_IP_DATA_FILE"];
        DNSMASQ_DATA_FILE = ENVIRON["I_DNSMASQ_DATA_FILE"];
        USER_ENTRIES_STATUS_FILE = ENVIRON["I_USER_ENTRIES_STATUS_FILE"];
        INSTANCE_ENTRIES_FILE = ENVIRON["I_INSTANCE_ENTRIES_FILE"];
        ENABLE_IDN=ENVIRON["U_ENABLE_IDN"];
        IP_FILTER=ENVIRON["U_IP_FILTER"];
        IP_FILTER_TYPE=ENVIRON["BLLIST_IP_FILTER_TYPE"];
        IP_FILTER_FILE=ENVIRON["BLLIST_IP_FILTER_FILE"];
        IP_EXCLUDED_ENABLE=ENVIRON["U_IP_EXCLUDED_ENABLE"];
        IP_EXCLUDED_FILE=ENVIRON["BLLIST_IP_EXCLUDED_FILE"];
        FQDN_FILTER=ENVIRON["U_FQDN_FILTER"];
        FQDN_FILTER_TYPE=ENVIRON["BLLIST_FQDN_FILTER_TYPE"];
        FQDN_FILTER_FILE=ENVIRON["BLLIST_FQDN_FILTER_FILE"];
        FQDN_EXCLUDED_ENABLE=ENVIRON["U_FQDN_EXCLUDED_ENABLE"];
        FQDN_EXCLUDED_FILE=ENVIRON["BLLIST_FQDN_EXCLUDED_FILE"];
        STRIP_WWW=ENVIRON["U_STRIP_WWW"];
        SD_LIMIT=(+ENVIRON["U_SD_LIMIT"]);
        GR_EXCLUDED_SLD_FILE=ENVIRON["BLLIST_GR_EXCLUDED_SLD_FILE"];
        GR_EXCLUDED_MASKS_FILE=ENVIRON["BLLIST_GR_EXCLUDED_SLD_MASKS_FILE"];

        exit_code = 0;

        gsub("\042", "%22", U_ENTRIES_REMOTE);
        gsub("\047", "%27", U_ENTRIES_REMOTE);
        split(U_ENTRIES_REMOTE, urls, /[\040\011\012]+/);

        ip_pattern = "^[0-9]{1,3}([.][0-9]{1,3}){3}([\057][0-9]{1,2})?$";
        dns_serv_pattern = "[ ][0-9]{1,3}([.][0-9]{1,3}){3}([#][0-9]{2,5})?"
        fqdn_pattern_ascii = "^([a-z0-9._-]+[.])*([a-z]{2,}|xn--[a-z0-9]+)(" dns_serv_pattern ")?$";
        fqdn_pattern_cyr = "^([a-z0-9.-])*[^a-zA-Z.]+[.]([a-z]|[^a-z]){2,}(" dns_serv_pattern ")?$";

        delete fqdn_patterns_array
        delete ip_patterns_array
        delete gr_sld_excluded_array
        delete gr_mask_excluded_array
        delete ip_array;
        delete fqdn_array;
        delete dns_array;
        delete sld_array;
        delete ip_excluded_array;
        delete fqdn_excluded_array;
        delete download_results;

        if(IP_FILTER == 1) {
            pattern="";
            while((getline pattern <IP_FILTER_FILE) > 0) {
                if(pattern ~ /^[^#]/ && length(pattern) > 0) {
                    ip_patterns_array[pattern];
                };
            };
            close(IP_FILTER_FILE);
        };
        if(FQDN_FILTER == 1) {
            pattern="";
            while((getline pattern <FQDN_FILTER_FILE) > 0) {
                if(pattern ~ /^[^#]/ && length(pattern) > 0) {
                    fqdn_patterns_array[pattern];
                };
            };
            close(FQDN_FILTER_FILE);
        };
        if(SD_LIMIT != 0) {
            sld="";
            while((getline sld <GR_EXCLUDED_SLD_FILE) > 0) {
                if(sld ~ /^[^#]/ && length(sld) > 0) {
                    gr_sld_excluded_array[sld];
                };
            };
            close(GR_EXCLUDED_SLD_FILE);
            mask="";
            while((getline mask <GR_EXCLUDED_MASKS_FILE) > 0) {
                if(mask ~ /^[^#]/ && length(mask) > 0) {
                    gr_mask_excluded_array[mask];
                };
            };
            close(GR_EXCLUDED_MASKS_FILE);
        };
        if(IP_EXCLUDED_ENABLE == 1) {
            ip="";
            while((getline ip <IP_EXCLUDED_FILE) > 0) {
                if(ip ~ /^[^#]/ && length(ip) > 0) {
                    ip_excluded_array[ip];
                };
            };
            close(IP_EXCLUDED_FILE);
        };
        if(FQDN_EXCLUDED_ENABLE == 1) {
            fqdn="";
            while((getline fqdn <FQDN_EXCLUDED_FILE) > 0) {
                if(fqdn ~ /^[^#]/ && length(fqdn) > 0) {
                    fqdn_excluded_array[fqdn];
                };
            };
            close(FQDN_EXCLUDED_FILE);
        };
    }
    function makeLogRecord(level, msg) {
        if(ENABLE_LOGGING == 1) {
            system(sprintf("%s %s -p \"user.%s\" \"%s\"", LOGGER_CMD, LOGGER_PARAMS, level, msg));
        };
    };
    function checkExpr(val, array, invert,  _pattern) {
        for(_pattern in array) {
            if(val ~ _pattern) {
                return (+invert) ? 0 : 1;
            };
        };
        return (+invert) ? 1 : 0;
    };
    function getSld(val) {
        return substr(val, match(val, /[a-z0-9_-]+[.][a-z0-9-]+$/));
    };
    function checkIp(val) {
        if(IP_EXCLUDED_ENABLE == 1 && val in ip_excluded_array) {
            return 0;
        };
        if((IP_FILTER == 1 && checkExpr(val, ip_patterns_array, IP_FILTER_TYPE) == 1) || val in ip_array) {
            return 0;
        };
        ip_array[val];
        return 1;
    };
    function checkFQDN(val,  _fqdn, _dns, _call_idn, _sld) {
        split(val, a, " ");
        _fqdn = a[1];
        _dns = a[2];
        sub(/[.]$/, "", _fqdn);
        sub(/^[\052][.]/, "", _fqdn);
        if(STRIP_WWW == 1) {
            sub(/^www[0-9]?[.]/, "", _fqdn);
        };
        if(FQDN_EXCLUDED_ENABLE == 1 && _fqdn in fqdn_excluded_array) {
            return 0;
        };
        if((FQDN_FILTER == 1 && checkExpr(_fqdn, fqdn_patterns_array, FQDN_FILTER_TYPE) == 1) || _fqdn in fqdn_array) {
            return 0;
        }
        if(ENABLE_IDN == 1 && _fqdn !~ fqdn_pattern_ascii && _fqdn ~ fqdn_pattern_cyr) {
            _call_idn = sprintf("%s %s", IDN_CMD, _fqdn);
            _call_idn | getline _fqdn;
            close(_call_idn);
            sub("\n", "", _fqdn);
        };
        if(_fqdn ~ fqdn_pattern_ascii) {
            if(length(_dns) > 0) {
                dns_array[_fqdn] = _dns;
            };
            if(SD_LIMIT == 0) {
                fqdn_array[_fqdn];
            } else {
                _sld = getSld(_fqdn);
                if(_sld in gr_sld_excluded_array || sld_array[_sld] < SD_LIMIT) {
                    if(length(gr_mask_excluded_array) > 0 && checkExpr(_fqdn, gr_mask_excluded_array, 0) == 1) {
                        return 0;
                    }
                    fqdn_array[_fqdn] = _sld;
                    if(_sld in sld_array) {
                        sld_array[_sld]++;
                    } else {
                        sld_array[_sld] = 1;
                    };
                };
            };
            return 1;
        };
        return 0;
    };
    function writeIpList(array,  _str) {
        _str = "";
        for(i in array) {
            _str = _str i ",";
        };
        return _str;
    };
    function writeDNSData(val, dns) {
        if(length(dns) == 0 && length(U_USER_ENTRIES_DNS) > 0) {
            dns = U_USER_ENTRIES_DNS;
        };
        if(length(dns) > 0) {
            printf "server=/%s/%s\n", val, dns >> DNSMASQ_DATA_FILE;
        };
        printf "nftset=/%s/%s#%s\n", val, NFT_TABLE_DNSMASQ, NFTSET_DNSMASQ >> DNSMASQ_DATA_FILE;
    };
    function writeFqdnEntries(  _fqdn, _sld, _fval) {
        for(_fqdn in fqdn_array) {
            if(SD_LIMIT == 0) {
                writeDNSData(_fqdn, dns_array[_fqdn]);
            } else {
                _sld = fqdn_array[_fqdn];
                _fval = _fqdn;
                if((!(_sld in fqdn_array) || _fqdn == _sld) && _sld in sld_array) {
                    if(!(_sld in gr_sld_excluded_array) && sld_array[_sld] >= SD_LIMIT) {
                        _fval = _sld;
                        delete sld_array[_sld];
                    };
                    writeDNSData(_fval, dns_array[_fval]);
                };
            };
        };
    };
    function trimEntry(str) {
        sub("\015", "", str);
        return str;
    };
    function checkEntry(str) {
        if (str ~ /^([\040\011]*$|#)/) {
            return 0;
        }
        else if(str ~ ip_pattern) {
            return 1;
        }
        else if(str ~ fqdn_pattern_ascii) {
            return 2;
        }
        else if(str ~ fqdn_pattern_cyr) {
            return 3;
        };
    };
    function readFile(fpath, fname,  _line, _ip_num, _fqdn_num, _ret) {
        _ip_num = 0; _fqdn_num = 0;
        while((getline _line <fpath) > 0) {
            _line = trimEntry(_line);
            _ret = checkEntry(_line);
            if(_ret == 1) {
                if(checkIp(_line)) {
                    _ip_num++;
                };
            }
            else if(_ret == 2 || _ret == 3) {
                if(checkFQDN(_line)) {
                    _fqdn_num++;
                };
            };
        };
        close(fpath);
        download_results[length(download_results)] = sprintf("%s %s %s:%s",
            _ip_num, _fqdn_num, U_NAME, fname);
    };
    function downloadFile(url,  _, _i, _ret_code, _wget_call, _ip_array, _fqdn_array, _val, _ret) {
        if(length(url) == 0) {
            return 1;
        };

        _ret_code = 1;
        _wget_call = sprintf("%s %s - \"%s\"; printf \"\n$?\n\"", WGET_CMD, WGET_PARAMS, url);
        _ip_num = 0;
        _fqdn_num = 0;

        delete _ip_array;
        delete _fqdn_array;

        for(_i = 1; _i <= DOWNLOAD_ATTEMPTS; _i++) {
            delete _ip_array;
            delete _fqdn_array;

            while((_wget_call | getline _val) > 0) {
                if(_val ~ /^[0-9]{1,3}$/) {
                    continue;
                };
                _val = trimEntry(_val);
                _ret = checkEntry(_val);
                if(_ret == 1) {
                    _ip_array[_val];
                }
                else if(_ret == 2) {
                    _fqdn_array[_val];
                };
            };
            close(_wget_call);

            if(_val ~ /^[0-9]{1,3}$/) {
                _ret_code = _val;
            };
            if(_ret_code == 0) {
                break;
            };

            makeLogRecord("err", sprintf(attempt_err_pattern, _i, U_NAME, url));
            printf(" " attempt_err_pattern "\n", _i, U_NAME, url) > stderr;

            if(_i >= DOWNLOAD_ATTEMPTS) {
                break;
            };
            sleep | getline _;
            close(sleep);
        };

        if(_ret_code == 0 && (length(_ip_array) > 0 || length(_fqdn_array) > 0)) {
            for(_i in _ip_array) {
                if(checkIp(_i)) {
                    _ip_num++;
                };
            };
            for(_i in _fqdn_array) {
                if(checkFQDN(_i)) {
                    _fqdn_num++;
                };
            };
        };

        download_results[length(download_results)] = sprintf("%s %s %s:%s",
            _ip_num, _fqdn_num, U_NAME, url);

        return _ret_code;
    };
    END {
        readFile(INSTANCE_ENTRIES_FILE, "local");
        if(ENTRIES_ADDITIONAL_FILE_ENABLE == 1) {
            readFile(ENTRIES_ADDITIONAL_FILE, ENTRIES_ADDITIONAL_FILE);
        };
        dl_ret_code = 1;
        for(i in urls) {
            url = urls[i];
            dl_ret_code = downloadFile(url);
            if(dl_ret_code != 0) {
                exit_code = dl_ret_code;
                if(ENABLE_TMP_DOWNLOADS == 1) {
                    break;
                };
            };
        };
        if(ENABLE_TMP_DOWNLOADS != 1 || (ENABLE_TMP_DOWNLOADS == 1 && exit_code == 0)) {
            if(length(ip_array) > 0) {
                printf "table %s {\n%s", NFT_TABLE, NFTSET_IP_STRING >> IP_DATA_FILE;
                if(length(ip_array) > 0) {
                    printf "elements={%s};", writeIpList(ip_array) >> IP_DATA_FILE;
                };
                printf "}\n}\n" >> IP_DATA_FILE;
            };
            writeFqdnEntries();
            for(i in download_results) {
                print download_results[i] >> USER_ENTRIES_STATUS_FILE;
            };
        };
        exit exit_code;
    }'

exit $?
